from __future__ import annotations

"""V18.3 MuJoCo camera-based orange cube detector.

Compared with V18.2, this version keeps the visible camera marker and adds
calibration support:
    - default XY calibration offset for immediate demo use;
    - optional saved calibration JSON generated by --calibrate-vision;
    - raw + calibrated coordinates are logged for easier debugging.

The detector still uses lightweight RGB color segmentation + camera geometry.
This is intentional for the current simulation task: one orange cube, stable
background, fast and robust progress demo.
"""

from dataclasses import dataclass
from pathlib import Path
import csv
import json
import math
import re
import time
from typing import Optional, Tuple

import mujoco
import numpy as np


CAMERA_NAME = "vision_overhead"
IMAGE_WIDTH = 640
IMAGE_HEIGHT = 480

# Stable fallback calibration from V18.2. V18.3 can automatically generate a
# better offset and store it in outputs/.../vision_calibration_v18_3.json.
DEFAULT_VISION_XY_CALIBRATION_OFFSET = np.array([-0.010, -0.032, 0.0], dtype=float)


@dataclass
class CubeDetection:
    detected: bool
    pixel_center: Tuple[float, float]
    bbox: Tuple[int, int, int, int]
    area: int
    raw_world_pos: np.ndarray
    calibration_offset: np.ndarray
    stable_world_pos: np.ndarray
    planner_cube_pos: np.ndarray
    source: str
    debug_image_path: str = ""
    message: str = ""


VISION_CAMERA_XML = '''
    <!-- V18.3 vision demo overhead camera. Camera looks downward along world -Z. -->
    <camera name="vision_overhead" pos="0.55 0.00 1.80" xyaxes="1 0 0 0 1 0" fovy="45"/>
'''

# MuJoCo <camera> itself is virtual and normally invisible in the viewer.
# This marker is only for demonstration: it does not collide and does not
# participate in physics. It makes the camera position easy to explain.
VISION_CAMERA_MARKER_XML = '''
    <!-- V18.3 visible camera marker for demo only: no collision, no physics. -->
    <body name="vision_camera_marker" pos="0.55 0.00 1.80">
        <geom name="vision_camera_marker_body"
              type="box"
              size="0.040 0.028 0.020"
              rgba="0.05 0.05 0.05 1"
              contype="0"
              conaffinity="0"/>
        <geom name="vision_camera_marker_lens"
              type="cylinder"
              pos="0 0 -0.028"
              size="0.014 0.012"
              rgba="0.00 0.00 0.00 1"
              contype="0"
              conaffinity="0"/>
        <geom name="vision_camera_marker_view_axis"
              type="capsule"
              fromto="0 0 -0.040 0 0 -0.220"
              size="0.003"
              rgba="0.10 0.30 1.00 0.55"
              contype="0"
              conaffinity="0"/>
    </body>
'''


def ensure_vision_xml(source_xml: Path, vision_xml: Path, camera_name: str = CAMERA_NAME) -> Path:
    """Create/update a MuJoCo XML with an overhead camera and visible marker.

    If source_xml is the normal demo XML, the original file is not modified.
    The output is v2/demo_vision.xml by default. If demo_vision.xml already
    exists, this function can still add the missing camera/marker.
    """
    source_xml = Path(source_xml)
    vision_xml = Path(vision_xml)
    if not source_xml.exists():
        raise FileNotFoundError(f"source XML not found: {source_xml}")

    text = source_xml.read_text(encoding="utf-8")
    if "<worldbody" not in text:
        raise RuntimeError("XML 中没有找到 <worldbody>，无法自动插入视觉相机。")

    has_camera = (f'name="{camera_name}"' in text) or (f"name='{camera_name}'" in text)
    has_marker = ('name="vision_camera_marker"' in text) or ("name='vision_camera_marker'" in text)

    insert_blocks = ""
    if not has_camera:
        insert_blocks += VISION_CAMERA_XML
    if not has_marker:
        insert_blocks += VISION_CAMERA_MARKER_XML

    if insert_blocks:
        text = re.sub(r"(<worldbody[^>]*>)", r"\1\n" + insert_blocks, text, count=1)

    vision_xml.parent.mkdir(parents=True, exist_ok=True)
    vision_xml.write_text(text, encoding="utf-8")
    return vision_xml


def load_calibration_offset(path: Path, default: np.ndarray = DEFAULT_VISION_XY_CALIBRATION_OFFSET) -> tuple[np.ndarray, str]:
    """Load calibration offset from JSON if available, otherwise return default."""
    path = Path(path)
    if path.exists():
        try:
            obj = json.loads(path.read_text(encoding="utf-8"))
            offset = np.asarray(obj.get("xy_offset", default.tolist()), dtype=float)
            if offset.shape == (2,):
                offset = np.array([offset[0], offset[1], 0.0], dtype=float)
            if offset.shape == (3,):
                return offset, f"loaded:{path}"
        except Exception as exc:
            return np.asarray(default, dtype=float), f"default_after_load_failed:{exc}"
    return np.asarray(default, dtype=float), "default_v18_2_offset"


def save_calibration_offset(path: Path, offset: np.ndarray, points: list[dict], camera_name: str = CAMERA_NAME) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    offset = np.asarray(offset, dtype=float)
    obj = {
        "version": "v18.3",
        "created_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "camera_name": camera_name,
        "xy_offset": [float(offset[0]), float(offset[1]), 0.0],
        "method": "median(true_stable_xy - raw_camera_backprojection_xy)",
        "points": points,
    }
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding="utf-8")


class OrangeCubeDetector:
    def __init__(
        self,
        model,
        data,
        camera_name: str = CAMERA_NAME,
        width: int = IMAGE_WIDTH,
        height: int = IMAGE_HEIGHT,
        debug_dir: Optional[Path] = None,
        calibration_offset: Optional[np.ndarray] = None,
    ):
        self.model = model
        self.data = data
        self.camera_name = camera_name
        self.width = int(width)
        self.height = int(height)
        self.debug_dir = Path(debug_dir) if debug_dir is not None else None
        if self.debug_dir is not None:
            self.debug_dir.mkdir(parents=True, exist_ok=True)

        self.calibration_offset = (
            np.asarray(calibration_offset, dtype=float).copy()
            if calibration_offset is not None
            else DEFAULT_VISION_XY_CALIBRATION_OFFSET.copy()
        )
        if self.calibration_offset.shape == (2,):
            self.calibration_offset = np.array([self.calibration_offset[0], self.calibration_offset[1], 0.0], dtype=float)

        self.camera_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_CAMERA, camera_name)
        if self.camera_id == -1:
            raise ValueError(f"找不到相机：{camera_name}。请确认 demo_vision.xml 已生成并被加载。")

    def set_calibration_offset(self, offset: np.ndarray) -> None:
        offset = np.asarray(offset, dtype=float)
        if offset.shape == (2,):
            offset = np.array([offset[0], offset[1], 0.0], dtype=float)
        if offset.shape != (3,):
            raise ValueError("calibration offset must have shape (2,) or (3,)")
        self.calibration_offset = offset.copy()

    def render_rgb(self) -> np.ndarray:
        renderer = mujoco.Renderer(self.model, height=self.height, width=self.width)
        renderer.update_scene(self.data, camera=self.camera_name)
        rgb = renderer.render()
        try:
            renderer.close()
        except Exception:
            pass
        return rgb

    def segment_orange(self, rgb: np.ndarray) -> np.ndarray:
        """Return a binary mask for the orange cube."""
        arr = rgb.astype(np.float32)
        r, g, b = arr[..., 0], arr[..., 1], arr[..., 2]
        # MuJoCo 3.9 renders the illuminated orange top face around
        # RGB=(255, 229, 137).  The old g<210 gate therefore rejected the
        # actual cube and fell back to the simulator body pose.  Ratio gates
        # keep the detector selective while covering both the older, darker
        # renderer output and the current brighter output.
        mask = (
            (r > 140.0)
            & (g > 70.0)
            & (b < 180.0)
            & (r > g * 1.05)
            & (g > b * 1.25)
        )
        return mask

    def _camera_ray_world(self, pixel_u: float, pixel_v: float) -> tuple[np.ndarray, np.ndarray]:
        mujoco.mj_forward(self.model, self.data)
        cam_pos = self.data.cam_xpos[self.camera_id].copy()
        cam_mat = self.data.cam_xmat[self.camera_id].reshape(3, 3).copy()

        fovy = float(self.model.cam_fovy[self.camera_id])
        if fovy <= 0:
            fovy = 45.0
        fy = 0.5 * self.height / math.tan(math.radians(fovy) / 2.0)
        fx = fy
        cx = (self.width - 1) / 2.0
        cy = (self.height - 1) / 2.0

        x = (float(pixel_u) - cx) / fx
        y = -(float(pixel_v) - cy) / fy
        ray_cam = np.array([x, y, -1.0], dtype=float)
        ray_cam = ray_cam / max(np.linalg.norm(ray_cam), 1e-9)
        ray_world = cam_mat @ ray_cam
        ray_world = ray_world / max(np.linalg.norm(ray_world), 1e-9)
        return cam_pos, ray_world

    def pixel_to_world_on_plane(self, pixel_u: float, pixel_v: float, plane_z: float) -> np.ndarray:
        origin, direction = self._camera_ray_world(pixel_u, pixel_v)
        denom = direction[2]
        if abs(float(denom)) < 1e-8:
            raise RuntimeError("camera ray is parallel to target plane; cannot back-project pixel")
        t = (float(plane_z) - origin[2]) / denom
        return origin + t * direction

    def _save_debug_image(self, rgb: np.ndarray, mask: np.ndarray, bbox: tuple[int, int, int, int], task_id: str) -> str:
        if self.debug_dir is None:
            return ""
        out_path = self.debug_dir / f"{task_id}_detection.png"
        try:
            import matplotlib.pyplot as plt
            fig, ax = plt.subplots(figsize=(8, 6), dpi=120)
            ax.imshow(rgb)
            x0, y0, x1, y1 = bbox
            ax.add_patch(plt.Rectangle((x0, y0), x1 - x0, y1 - y0, fill=False, linewidth=2))
            ax.scatter([(x0 + x1) / 2.0], [(y0 + y1) / 2.0], s=30)
            ax.set_title("V18.3 orange cube detection")
            ax.axis("off")
            fig.tight_layout()
            fig.savefig(out_path)
            plt.close(fig)
            return str(out_path)
        except Exception:
            try:
                from PIL import Image
                Image.fromarray(rgb).save(out_path)
                return str(out_path)
            except Exception:
                return ""

    def detect(
        self,
        task_id: str,
        planner_spawn_z: float = 1.050,
        stable_cube_z: float = 1.025,
        apply_calibration: bool = True,
        rgb: Optional[np.ndarray] = None,
    ) -> CubeDetection:
        rgb = self.render_rgb() if rgb is None else np.asarray(rgb)
        mask = self.segment_orange(rgb)
        ys, xs = np.where(mask)
        if len(xs) < 20:
            # Last-resort fallback for debugging; report marks this as fallback.
            try:
                cube_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_BODY, "orange_cube")
                stable = self.data.xpos[cube_id].copy()
                planner = np.array([stable[0], stable[1], planner_spawn_z], dtype=float)
                return CubeDetection(
                    detected=False,
                    pixel_center=(float("nan"), float("nan")),
                    bbox=(-1, -1, -1, -1),
                    area=0,
                    raw_world_pos=stable.copy(),
                    calibration_offset=np.zeros(3, dtype=float),
                    stable_world_pos=stable,
                    planner_cube_pos=planner,
                    source="fallback_body_xpos",
                    message="orange mask too small; used MuJoCo body xpos fallback",
                )
            except Exception:
                raise RuntimeError("视觉检测失败：没有找到 orange cube 的颜色区域。")

        x0, x1 = int(xs.min()), int(xs.max())
        y0, y1 = int(ys.min()), int(ys.max())
        u = float(xs.mean())
        v = float(ys.mean())
        area = int(len(xs))

        raw_world = self.pixel_to_world_on_plane(u, v, plane_z=stable_cube_z)
        raw_world[2] = float(stable_cube_z)
        offset = self.calibration_offset.copy() if apply_calibration else np.zeros(3, dtype=float)
        stable_world = raw_world + offset
        stable_world[2] = float(stable_cube_z)
        planner_cube_pos = np.array([stable_world[0], stable_world[1], planner_spawn_z], dtype=float)
        debug_path = self._save_debug_image(rgb, mask, (x0, y0, x1, y1), task_id)

        source = "rgb_color_segmentation+camera_backprojection"
        if apply_calibration:
            source += "+xy_calibration"
        return CubeDetection(
            detected=True,
            pixel_center=(u, v),
            bbox=(x0, y0, x1, y1),
            area=area,
            raw_world_pos=raw_world,
            calibration_offset=offset,
            stable_world_pos=stable_world,
            planner_cube_pos=planner_cube_pos,
            source=source,
            debug_image_path=debug_path,
            message=(
                "detected orange cube from MuJoCo camera RGB image; "
                f"raw_world=({raw_world[0]:.4f},{raw_world[1]:.4f},{raw_world[2]:.4f}); "
                f"calib_offset=({offset[0]:.4f},{offset[1]:.4f},{offset[2]:.4f})"
            ),
        )


def init_detection_log(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "timestamp",
            "task_id",
            "detected",
            "source",
            "pixel_u",
            "pixel_v",
            "bbox_x0",
            "bbox_y0",
            "bbox_x1",
            "bbox_y1",
            "area",
            "raw_x",
            "raw_y",
            "raw_z",
            "calib_dx",
            "calib_dy",
            "calib_dz",
            "stable_x",
            "stable_y",
            "stable_z",
            "planner_x",
            "planner_y",
            "planner_z",
            "debug_image_path",
            "message",
        ])


def append_detection_log(path: Path, task_id: str, det: CubeDetection) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    x0, y0, x1, y1 = det.bbox
    with open(path, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            time.strftime("%Y-%m-%d %H:%M:%S"),
            task_id,
            bool(det.detected),
            det.source,
            det.pixel_center[0],
            det.pixel_center[1],
            x0,
            y0,
            x1,
            y1,
            det.area,
            float(det.raw_world_pos[0]),
            float(det.raw_world_pos[1]),
            float(det.raw_world_pos[2]),
            float(det.calibration_offset[0]),
            float(det.calibration_offset[1]),
            float(det.calibration_offset[2]),
            float(det.stable_world_pos[0]),
            float(det.stable_world_pos[1]),
            float(det.stable_world_pos[2]),
            float(det.planner_cube_pos[0]),
            float(det.planner_cube_pos[1]),
            float(det.planner_cube_pos[2]),
            det.debug_image_path,
            det.message,
        ])
